// Implementations of the four TestAPI methods the M1 grading harness
// (tests/test.cpp) calls into. The header (tests/test_api.h) is marked
// "DO NOT MODIFY" — it is supplied by the course staff and replaced at
// grading time. This file is the adapter from those signatures into
// the project's loader/tokenizer/matmul code.
//
// Both shared helpers below construct a single static instance per
// process so repeated TestAPI calls don't re-parse the tokenizer or
// re-mmap the embedding dump.

#include "test_api.h"
#include "config.h"
#include "loader.h"
#include "tokenizer.h"
#include "kernel/kernels.cuh"
#include <memory>

namespace {
// Process-wide tokenizer instance. The vocab parse (~128k entries) is
// non-trivial, so the instance is cached across calls.
BPETokenizer &shared_tokenizer() {
    static BPETokenizer tok(TOKENIZER_PATH);
    return tok;
}

// Process-wide loader with the embedding payload already cached.
// The IIFE (immediately-invoked lambda) ensures the load happens
// exactly once during static initialization.
LlamaDumpLoader &shared_embeddings_loader() {
    static LlamaDumpLoader loader(DumpFloatType::BF16);
    static const bool loaded = []() {
        if (!loader.load_embeddings("assets/llama3/dump/embeddings.bin",
                                    EMBEDDING_DIM)) {
            throw runtime_error("failed to load embeddings dump file");
        }
        return true;
    }();
    (void)loaded;
    return loader;
}
} // namespace

// M1 Step 2: tokenize. The grading harness expects BOS prepended
// (the test fixtures were generated by a Python tokenizer that
// always emits <|begin_of_text|> at index 0).
vector<int> TestAPI::tokenize(string input) {
    BPETokenizer &tok = shared_tokenizer();
    vector<int> token_ids = tok.encode(input);
    token_ids.insert(token_ids.begin(), tok.bos_id());
    return token_ids;
}

// M1 Step 2 (inverse): detokenize an ID sequence back to text.
string TestAPI::detokenize(vector<int> token_ids) {
    BPETokenizer &tok = shared_tokenizer();
    return tok.decode(token_ids);
}

// M1 Step 4: embedding lookup. Returns the [s, EMBEDDING_DIM] FP32
// matrix for the given token IDs, copied into a std::vector so the
// test harness can compare against its golden fixture without owning
// raw heap pointers.
vector<float> TestAPI::get_embeddings(vector<int> token_ids) {
    LlamaDumpLoader &loader = shared_embeddings_loader();
    std::unique_ptr<float_t[]> raw(loader.get_embeddings(token_ids));
    const size_t total = token_ids.size() * static_cast<size_t>(EMBEDDING_DIM);
    vector<float> out(raw.get(), raw.get() + total);
    return out;
}

// M1 Step 5: matmul. Routes through the same gpu_matmul host entry
// the rest of the project uses — no separate test-only code path —
// so passing this test means the production kernel works.
vector<float> TestAPI::matmul(const vector<float> &A, const vector<float> &B,
                              int M, int K, int N) {
    if (M < 0 || K < 0 || N < 0) {
        throw runtime_error("matmul dimensions must be non-negative");
    }
    const size_t mk = static_cast<size_t>(M) * static_cast<size_t>(K);
    const size_t kn = static_cast<size_t>(K) * static_cast<size_t>(N);
    const size_t mn = static_cast<size_t>(M) * static_cast<size_t>(N);

    if (A.size() != mk) {
        throw runtime_error("matmul A size mismatch");
    }
    if (B.size() != kn) {
        throw runtime_error("matmul B size mismatch");
    }

    vector<float> C(mn, 0.0f);
    gpu_matmul(A.data(), B.data(), C.data(), M, K, N);
    return C;
}
